### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dnsext#2]
- [x] Getting rid or `Text`. Using `ShortByteString` only.
- [x] Test cases for types
- [x] Hiding constructors of RRs
- [x] API to add a new RR
- [x] IO
- [x] Resolver
- [x] diglike
- [x] cache
- [x] Separating DNSSEC
- [x] Extend Resolver to add new Resource Data

**Comment by kazu-yamamoto** [comment]
Done.
