### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dnsext#31]
- [x] Flatten RR
- [x] Builder side of SVCB
- [x] Brush up docmentation
- [x] Protecting against a large length and length-exceeded content data.
